### ISSUE TITLE
Unable to reproduce plots for human data

### ISSUE THREAD

**Issue by sashamain** [rchereji/plot2DO#12]
Hi there,

I was able to use this package and the yeast example data to reproduce the figures in your examples. However, when I downloaded the human example data I couldn't. When I run:

Rscript plot2DO.R --file=/path/human_SRR1781839.5M_reads.bam -g hg19 -m 0.015 --simplifyPlot=on --minLength=100 --maxLength=200

I get the following error:
![image](https://user-images.githubusercontent.com/59744754/136851015-2093cdf4-a264-4a95-a832-982195bc10bf.png)

Not sure if it has to do with the default annotation file? Any suggestions on how to get this to work would be appreciated.

Thank you

**Comment by rchereji** [comment]
Hi. 
I run the same command but I didn't get an error. 
In your case, there seems to be some issue with the connection to Ensembl server. Either the Ensembl server was down or your internet connection had an issue. Hopefully this was solved by now, and you can try running the command again.

**Comment by sashamain** [comment]
Hi, sorry for my delay in follow-up. I had to put this project on the back burner for a while.

 I reran this code and the similar line for the sample yeast data. Once again, I am able to reproduce the yeast plots but not those for human. If the Ensembl or the server were down, why am I able to still reproduce your yeast figures? Do they not rely on Ensembl?

Thank you

**Comment by paulati** [comment]
Hi sashamain,
here you can configure the file / mart source of annotations for each specie:
https://github.com/rchereji/plot2DO/blob/master/config/annotation_config.yaml
If you know an alternative source for human annotations you can change it in this file.
Annotations for sacCer3 are read from a local folder (annotations/sacCer3_chromInfo.txt) instead of from ensemble, a similar approach for human could work if you can't connect ensembl.
